version: 2.0
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: quay.io/haskell_works/stack-build-cabal:latest

    steps:
      - checkout

      ##### Copying scripts
      - run:
          name: Copying scripts
          command: |
            mkdir -p ~/.local/bin
            cp ./scripts/* ~/.local/bin

      - run:
          name: Query resolver & ghc version
          command: |
            resolver > resolver.conf
            ghc-version $(cat resolver.conf) >  ghc-version.conf

      ##### Building library
      - restore_cache:
          keys:
            - dot-stack-{{ checksum "stack.yaml"         }}-{{ checksum "package.yaml" }}-gz8vvsw
            - dot-stack-{{ checksum "resolver.conf"      }}-build-gz8vvsw
            - dot-stack-{{ checksum "ghc-version.conf"   }}-build-gz8vvsw
            - dot-stack-{{ checksum "resolver.conf"      }}-setup-gz8vvsw
            - dot-stack-{{ checksum "ghc-version.conf"   }}-setup-gz8vvsw

      - restore_cache:
          keys:
            - dot-stack-work-{{ checksum "resolver.conf"      }}-gz8vvsw
            - dot-stack-work-{{ checksum "ghc-version.conf"   }}-gz8vvsw

      - run:
          name: Stack setup
          command: stack setup

      - save_cache:
          key:    dot-stack-{{ checksum "resolver.conf"      }}-setup-gz8vvsw
          paths:  ~/.stack
      - save_cache:
          key:    dot-stack-{{ checksum "ghc-version.conf"   }}-setup-gz8vvsw
          paths:  ~/.stack

      - run:
          name: Compiling
          command: stack build --test --no-run-tests

      - save_cache:
          key:    dot-stack-{{ checksum "stack.yaml"         }}-{{ checksum "package.yaml" }}-gz8vvsw
          paths:  ~/.stack
      - save_cache:
          key:    dot-stack-{{ checksum "resolver.conf"      }}-build-gz8vvsw
          paths:  ~/.stack
      - save_cache:
          key:    dot-stack-{{ checksum "ghc-version.conf"   }}-build-gz8vvsw
          paths:  ~/.stack
      - save_cache:
          key:    dot-stack-work-{{ checksum "resolver.conf" }}-gz8vvsw
          paths:  ~/project/.stack-work

      ##### Running tests
      - run:
          name: Running tests
          command: |
            stack test
