name:                lru-cache
version:             0.1.1.0
github:              "packetloop/lru-cache"
license:             BSD3
author:              "John Ky"
maintainer:          "jky@arbor.net"
copyright:           "2018 John Ky"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/packetloop/lru-cache#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- hw-fingertree-strict
- lens
- stm

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  lru-cache-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lru-cache
