name:                s3-lru-cache
version:             0.1.0.0
github:              "packetloop/s3-lru-cache"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/packetloop/s3-lru-cache#readme>

dependencies:
- base >= 4.7 && < 5
- amazonka
- amazonka-core
- amazonka-s3
- bytestring
- conduit-extra
- lens
- resourcet
- stm

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  s3-lru-cache-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - s3-lru-cache
