name:                arbor-lru-cache
version:             0.1.1.0
github:              "packetloop/arbor-lru-cache"
license:             MIT
author:              "Arbor Networks"
maintainer:          "mayhem@arbor.net"
copyright:           "2018 Arbor Networks"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/packetloop/arbor-lru-cache#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- generic-lens
- lens
- stm

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  arbor-lru-cache-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hedgehog
    - hspec
    - hw-hspec-hedgehog
    - arbor-lru-cache
